apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongoclaw

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  # Uncomment to enable ingress
  # - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mongoclaw
  app.kubernetes.io/part-of: mongoclaw

images:
  - name: mongoclaw
    newTag: latest
