apiVersion: v1
kind: Service
metadata:
  name: mongoclaw
  namespace: mongoclaw
  labels:
    app.kubernetes.io/name: mongoclaw
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mongoclaw
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: mongoclaw-headless
  namespace: mongoclaw
  labels:
    app.kubernetes.io/name: mongoclaw
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mongoclaw
    app.kubernetes.io/component: server
